server:
  port: 9093

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
#    pool:
#      enabled: true
#      max-connections: 20
#      idle-timeout: 30000