
server:
  port: 8082

logging:
  level:
    root: info
dubbo:
  application:
    name: consumer
  protocol:
    name: dubbo
    port: 29090
  registry:
    address: zookeeper://localhost:2181
  consumer:
    check: false
spring:
  thymeleaf:
    cache: false